"""
English -> Hindi parallel corpus for the urine strip report (sentence level),
plus a clinical CONSISTENCY checker (no torch needed).

The English side mirrors report_generator.py line for line. The Hindi side is
written from templates: HAVE A HINDI READER PROOFREAD the strings below
(HI_NAME, HI_DESC, HI_ASSOC, ADV_HI, the sentence patterns) before you rely on it.

Run in Colab:  %run hindi_data.py     -> writes parallel_en_hi.json
"""
import json
import random
import re
from itertools import combinations

random.seed(42)

# ---------------- tokenisers ----------------
EN_TOK = re.compile(r"\d+\.\d+|[+\-]?\d+|\w+|[^\w\s]")


def en_tok(s):
    return EN_TOK.findall(s)


def hi_tok(s):
    # NOTE: no regex here - Python's \w splits Devanagari words at vowel signs
    for ch in [",", "।", ":", "(", ")"]:
        s = s.replace(ch, f" {ch} ")
    return s.split()


def hi_join(tokens):
    s = " ".join(tokens)
    for ch in [",", "।", ":"]:
        s = s.replace(f" {ch}", ch)
    return s.replace("( ", "(").replace(" )", ")")


# ---------------- vocabulary of the report ----------------
ANALYTES = ["Glucose", "Protein", "Ketones", "Blood"]
ORDER = ["Glucose", "Protein", "Ketones", "Blood", "pH"]
HI_NAME = {"Glucose": "ग्लूकोज़", "Protein": "प्रोटीन", "Ketones": "कीटोन",
           "Blood": "रक्त", "pH": "पीएच"}
LEVEL = {2: "+1", 3: "+2", 4: "+3"}
EN_DESC = {2: "mildly elevated", 3: "moderately elevated", 4: "markedly elevated"}
HI_DESC = {2: "हल्का बढ़ा हुआ", 3: "मध्यम रूप से बढ़ा हुआ", 4: "काफ़ी बढ़ा हुआ"}
EN_ASSOC = {"Glucose": "diabetes or glycosuria",
            "Protein": "proteinuria or kidney disease",
            "Ketones": "ketosis, fasting or ketoacidosis",
            "Blood": "a urinary tract infection, hematuria or kidney stones"}
HI_ASSOC = {"Glucose": "मधुमेह या ग्लाइकोसुरिया",
            "Protein": "प्रोटीन्यूरिया या गुर्दे की बीमारी",
            "Ketones": "कीटोसिस, उपवास या कीटोएसिडोसिस",
            "Blood": "मूत्र मार्ग संक्रमण, हेमेट्यूरिया या गुर्दे की पथरी"}
# two phrasings: "assoc" is what report_generator.py writes; "ind" is a paraphrase
PHR = {"assoc": ("which may be associated with", "जो {x} से संबंधित हो सकता है"),
       "ind": ("which may indicate", "जो {x} का संकेत हो सकता है")}
ADV_EN = {"high": "Please consult a doctor for a proper evaluation.",
          "mild": "Consider repeating the test and discussing the result with a doctor."}
ADV_HI = {"high": "कृपया उचित मूल्यांकन के लिए डॉक्टर से परामर्श करें।",
          "mild": "कृपया जाँच दोहराएँ और परिणाम पर डॉक्टर से चर्चा करें।"}
TITLE = ("URINE STRIP REPORT", "मूत्र स्ट्रिप रिपोर्ट")
DISC = ("Note: this report is generated by a proof-of-concept system from a strip "
        "photo. It is not a clinical diagnosis. Please consult a qualified doctor.",
        "नोट: यह रिपोर्ट स्ट्रिप की तस्वीर से एक प्रूफ-ऑफ-कॉन्सेप्ट प्रणाली द्वारा बनाई गई है। "
        "यह चिकित्सीय निदान नहीं है। कृपया किसी योग्य डॉक्टर से परामर्श करें।")
NONE = ("Overall, no abnormal findings were detected on this strip.",
        "कुल मिलाकर, इस स्ट्रिप पर कोई असामान्य निष्कर्ष नहीं मिला।")
CONST = {TITLE[0]: TITLE[1], DISC[0]: DISC[1], NONE[0]: NONE[1]}


def _pair(en, hi, kind, key=None):
    return {"en": en, "hi": hi, "src": en_tok(en), "tgt": hi_tok(hi), "kind": kind, "key": key}


def analyte_pair(a, sev, phr="assoc"):
    verb = "were" if a == "Ketones" else "was"
    if sev == 0:
        return _pair(f"{a} {verb} not detected.", f"{HI_NAME[a]} नहीं पाया गया।",
                     "analyte", (a, sev, phr))
    en_p, hi_p = PHR[phr]
    if sev == 1:
        en_d, hi_d = "detected in trace amounts", "अल्प मात्रा में पाया गया"
    else:
        lv = LEVEL[sev]
        en_d, hi_d = f"{EN_DESC[sev]} ({lv})", f"{HI_DESC[sev]} ({lv}) था"
    en = f"{a} {verb} {en_d}, {en_p} {EN_ASSOC[a]}."
    hi = f"{HI_NAME[a]} {hi_d}, {hi_p.format(x=HI_ASSOC[a])}।"
    return _pair(en, hi, "analyte", (a, sev, phr))


def ph_pair(v):
    cat = "acidic" if v < 5.0 else "alkaline" if v > 8.0 else "typical"
    en_c = {"typical": "within the typical range", "acidic": "on the acidic side",
            "alkaline": "on the alkaline side"}[cat]
    hi_c = {"typical": "सामान्य सीमा के भीतर है", "acidic": "अम्लीय पक्ष में है",
            "alkaline": "क्षारीय पक्ष में है"}[cat]
    return _pair(f"Urine pH is {v:.1f}, which is {en_c}.",
                 f"मूत्र का पीएच {v:.1f} है, जो {hi_c}।", "ph")


def summary_pair(flagged, adv):
    en = f"Overall, abnormal findings were noted for: {', '.join(flagged)}. {ADV_EN[adv]}"
    hi = (f"कुल मिलाकर, इन जाँचों में असामान्य परिणाम मिले: "
          f"{', '.join(HI_NAME[f] for f in flagged)}। {ADV_HI[adv]}")
    return _pair(en, hi, "summary")


def build_all():
    pairs = []
    for a in ANALYTES:
        pairs.append(analyte_pair(a, 0))
        for sev in (1, 2, 3, 4):
            for phr in PHR:
                pairs.append(analyte_pair(a, sev, phr))
    for v in [x / 2 for x in range(8, 19)]:          # pH 4.0 ... 9.0 in 0.5 steps
        pairs.append(ph_pair(v))
    for r in range(1, 6):
        for sub in combinations(ORDER, r):
            for adv in ("mild", "high"):
                if adv == "high" and not any(x in ANALYTES for x in sub):
                    continue                          # 'high' needs an analyte >= +2
                pairs.append(summary_pair(list(sub), adv))
    for en, hi in (NONE, TITLE, DISC):
        pairs.append(_pair(en, hi, "other"))
    return pairs


# held-out (analyte, severity, phrasing) combinations: never seen in training
HELD = {("Ketones", 3, "assoc"), ("Blood", 4, "ind"), ("Glucose", 1, "ind"),
        ("Protein", 2, "assoc"), ("Ketones", 2, "ind"), ("Blood", 1, "assoc"),
        ("Glucose", 4, "assoc"), ("Protein", 3, "ind")}


def make_splits():
    pairs = build_all()
    test_combo = [p for p in pairs if p["kind"] == "analyte" and p["key"] in HELD]
    sums = [p for p in pairs if p["kind"] == "summary"]
    random.shuffle(sums)
    test_summary, val = sums[:10], sums[10:18]
    held_ids = {id(p) for p in test_combo + test_summary + val}
    train = [p for p in pairs if id(p) not in held_ids]
    return {"train": train, "val": val, "test_combo": test_combo,
            "test_summary": test_summary}


# ---------------- clinical consistency check ----------------
def expected_facts(en):
    """Read the facts out of the ENGLISH source line."""
    if en in CONST and en != NONE[0]:
        return {"kind": "const"}
    if en == NONE[0]:
        return {"kind": "none"}
    if en.startswith("Urine pH"):
        cat = "typical" if "typical" in en else "acidic" if "acidic" in en else "alkaline"
        return {"kind": "ph", "num": re.search(r"\d+\.\d", en).group(), "cat": cat}
    if en.startswith("Overall"):
        names = [n.strip() for n in en.split("for:")[1].split(".")[0].split(",")]
        return {"kind": "sum", "names": names,
                "adv": "high" if "Please consult a doctor" in en else "mild"}
    sev = (0 if "not detected" in en else 1 if "trace" in en else 2 if "mildly" in en
           else 3 if "moderately" in en else 4)
    lv = re.search(r"\+\d", en)
    return {"kind": "analyte", "a": en.split()[0], "sev": sev,
            "lv": lv.group() if lv else None}


def is_consistent(en, hi_tokens):
    """True if every clinical fact in the English line survives in the Hindi output."""
    f, toks = expected_facts(en), hi_tokens
    s = hi_join(toks)
    if f["kind"] in ("const", "none"):
        return s == hi_join(hi_tok(CONST[en]))
    if f["kind"] == "ph":
        cat = {"typical": "सामान्य सीमा के भीतर", "acidic": "अम्लीय पक्ष में",
               "alkaline": "क्षारीय पक्ष में"}[f["cat"]]
        return f["num"] in toks and HI_NAME["pH"] in toks and cat in s
    if f["kind"] == "sum":
        names = ", ".join(HI_NAME[n] for n in f["names"])
        return f"मिले: {names}।" in s and ADV_HI[f["adv"]] in s
    a, sev, lv = f["a"], f["sev"], f["lv"]
    if [n for n in HI_NAME.values() if n in toks] != [HI_NAME[a]]:
        return False                                   # missing / extra analyte
    if any(x in toks for x in LEVEL.values() if x != lv):
        return False                                   # wrong level
    if sev == 0:
        return "नहीं पाया गया" in s and HI_ASSOC[a] not in s
    if sev == 1:
        return "अल्प मात्रा में पाया गया" in s and HI_ASSOC[a] in s
    return HI_DESC[sev] in s and f"({lv})" in s and HI_ASSOC[a] in s


if __name__ == "__main__":
    splits = make_splits()
    for sp in splits.values():
        for p in sp:
            p.pop("key", None)
    with open("parallel_en_hi.json", "w", encoding="utf-8") as f:
        json.dump(splits, f, ensure_ascii=False, indent=1)
    print({k: len(v) for k, v in splits.items()})
    ex = splits["test_combo"][0]
    print(ex["en"]); print(ex["hi"])
    ok = all(is_consistent(p["en"], p["tgt"]) for sp in splits.values() for p in sp)
    print("all references pass the consistency check:", ok)
