"""
Report generator: turns the urine strip reader's /analyze JSON into a
plain-language report (template-based NLG).

Input format (same as your FastAPI /analyze response):
{"results": {"Glucose": {"result": "+1"}, "Protein": {"result": "Trace"},
             "pH": {"result": "6.0"}, "Ketones": {"result": "Negative"},
             "Blood": {"result": "+2"}}}

Run in Colab:  %run report_generator.py     (prints a demo report)
Or import:     from report_generator import generate_report
"""

# severity order: negative < trace < +1 < +2 < +3
LEVEL_ORDER = {"negative": 0, "trace": 1, "+1": 2, "+2": 3, "+3": 4}

DESCRIPTORS = {
    0: "not detected",
    1: "detected in trace amounts",
    2: "mildly elevated",
    3: "moderately elevated",
    4: "markedly elevated",
}

# Hedged, general associations only (never a diagnosis)
ASSOCIATIONS = {
    "Glucose": "diabetes or glycosuria",
    "Protein": "proteinuria or kidney disease",
    "Ketones": "ketosis, fasting or ketoacidosis",
    "Blood": "a urinary tract infection, hematuria or kidney stones",
}

ADVICE = {
    "mild": "Consider repeating the test and discussing the result with a doctor.",
    "high": "Please consult a doctor for a proper evaluation.",
}

DISCLAIMER = (
    "Note: this report is generated by a proof-of-concept system from a strip "
    "photo. It is not a clinical diagnosis. Please consult a qualified doctor."
)


def normalize_level(raw):
    """Map '+1', '1+', 'Trace', 'NEGATIVE' ... to a key in LEVEL_ORDER."""
    s = str(raw).strip().lower().replace(" ", "")
    if s in ("neg", "negative", "-", "0", "nil"):
        return "negative"
    if s in ("trace", "tr", "+/-"):
        return "trace"
    if s.endswith("+") and s[:-1].isdigit():   # '2+' -> '+2'
        s = "+" + s[:-1]
    return s if s in LEVEL_ORDER else None


def describe_ph(raw):
    try:
        v = float(raw)
    except (TypeError, ValueError):
        return f"pH result: {raw}.", 0
    if v < 5.0:
        return f"Urine pH is {v:.1f}, which is on the acidic side.", 1
    if v > 8.0:
        return f"Urine pH is {v:.1f}, which is on the alkaline side.", 1
    return f"Urine pH is {v:.1f}, which is within the typical range.", 0


def generate_report(api_json):
    results = api_json.get("results", api_json)
    lines, flagged = [], []
    worst = 0

    for analyte in ("Glucose", "Protein", "Ketones", "Blood"):
        if analyte not in results:
            continue
        raw = results[analyte].get("result") if isinstance(results[analyte], dict) else results[analyte]
        level = normalize_level(raw)
        if level is None:
            lines.append(f"{analyte}: result '{raw}' could not be interpreted.")
            continue
        sev = LEVEL_ORDER[level]
        worst = max(worst, sev)
        verb = "were" if analyte == "Ketones" else "was"
        text = f"{analyte} {verb} {DESCRIPTORS[sev]}"
        if sev > 1:  # show the grade only when it adds information
            text += f" ({level})"
        if sev > 0:
            flagged.append(analyte)
            text += f", which may be associated with {ASSOCIATIONS[analyte]}"
        lines.append(text + ".")

    if "pH" in results:
        raw = results["pH"].get("result") if isinstance(results["pH"], dict) else results["pH"]
        text, ph_flag = describe_ph(raw)
        lines.append(text)
        if ph_flag:
            flagged.append("pH")

    if not flagged:
        summary = "Overall, no abnormal findings were detected on this strip."
    else:
        summary = f"Overall, abnormal findings were noted for: {', '.join(flagged)}."
        summary += " " + (ADVICE["high"] if worst >= 3 else ADVICE["mild"])

    return "\n".join(["URINE STRIP REPORT", "", *lines, "", summary, "", DISCLAIMER])


if __name__ == "__main__":
    demo = {"results": {
        "Glucose": {"result": "+1"},
        "Protein": {"result": "Trace"},
        "pH": {"result": "6.0"},
        "Ketones": {"result": "Negative"},
        "Blood": {"result": "+2"},
    }}
    print(generate_report(demo))
    print("\n----- all-normal example -----\n")
    print(generate_report({"results": {
        "Glucose": {"result": "Negative"}, "Protein": {"result": "Negative"},
        "pH": {"result": "6.5"}, "Ketones": {"result": "Negative"},
        "Blood": {"result": "Negative"},
    }}))
