// -----------------------------------------------------------------------
// pdfExport.js
//
// What this file does:
//   Builds a printable PDF report of a strip analysis (using the jsPDF
//   library) and triggers a browser download of it. All PDF layout
//   (positions, fonts, colors) is done manually with jsPDF's low-level
//   drawing API since it doesn't support HTML/CSS templates.
//
// Where it fits in the project:
//   Called by components/ResultsDisplay.jsx when the user clicks
//   "Download PDF report" after an analysis.
// -----------------------------------------------------------------------

import jsPDF from 'jspdf'

/**
 * Generates a clean, printable PDF report for a single strip analysis
 * and triggers a download.
 *
 * @param {object} params
 * @param {string} [params.filename] - Original uploaded image filename,
 *   shown in the report header and used to derive the PDF's filename.
 * @param {Object.<string, {detected_rgb: number[], result: string}>} params.results -
 *   The per-parameter analysis results, keyed by parameter name (e.g.
 *   "Glucose"), as returned by the backend's /analyze endpoint.
 * @param {string} [params.timestamp] - ISO date string for when the scan
 *   was run; defaults to "now" if omitted.
 */
export function exportResultsToPDF({ filename, results, timestamp }) {
  // 'pt' units and A4 page size keep the coordinate math below predictable
  // and consistent regardless of the viewer's system locale/paper size.
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 48
  let y = 56 // running vertical cursor, advanced manually as content is drawn

  // Header band — a thin colored bar across the top of the page for branding.
  doc.setFillColor(13, 124, 102) // teal
  doc.rect(0, 0, pageWidth, 8, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(16, 35, 31)
  doc.text('Urine Test Strip Analysis Report', margin, y)

  y += 22
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(90, 100, 98)
  const dateStr = timestamp ? new Date(timestamp).toLocaleString() : new Date().toLocaleString()
  doc.text(`Sample file: ${filename || 'uploaded image'}`, margin, y)
  y += 14
  doc.text(`Generated: ${dateStr}`, margin, y)
  y += 14
  doc.text('Method: Colorimetric image analysis (nearest-match against reference chart)', margin, y)

  y += 30
  doc.setDrawColor(215, 229, 224)
  doc.line(margin, y, pageWidth - margin, y)
  y += 28

  // Table header — fixed x-coordinates for each "column" of the results table.
  const col = {
    param: margin,
    swatch: margin + 140,
    rgb: margin + 200,
    result: margin + 340,
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(16, 35, 31)
  doc.text('Parameter', col.param, y)
  doc.text('Color', col.swatch, y)
  doc.text('Detected RGB', col.rgb, y)
  doc.text('Result', col.result, y)
  y += 10
  doc.setDrawColor(215, 229, 224)
  doc.line(margin, y, pageWidth - margin, y)
  y += 18

  doc.setFont('helvetica', 'normal')

  Object.entries(results || {}).forEach(([parameter, data]) => {
    // Defensive fallback to white in case a result is somehow missing its
    // detected_rgb, so drawing the swatch below never throws.
    const [r, g, b] = data.detected_rgb || [255, 255, 255]

    doc.setTextColor(16, 35, 31)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text(parameter, col.param, y + 4)

    // Small filled circle swatch showing the actual detected color, same
    // idea as the color box in ResultsDisplay.jsx but drawn manually
    // since PDF has no CSS backgroundColor equivalent.
    doc.setFillColor(r, g, b)
    doc.setDrawColor(200, 200, 200)
    doc.circle(col.swatch + 8, y, 8, 'FD')

    // Monospace font for the RGB triplet so the numbers align neatly
    // column-to-column down the page.
    doc.setFont('courier', 'normal')
    doc.setFontSize(9.5)
    doc.setTextColor(90, 100, 98)
    doc.text(`${r}, ${g}, ${b}`, col.rgb, y + 4)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10.5)
    doc.setTextColor(13, 87, 72)
    doc.text(String(data.result), col.result, y + 4)

    y += 30

    // jsPDF doesn't auto-paginate; once the cursor gets close to the
    // bottom margin of an A4 page (~842pt tall), manually start a new
    // page so long result lists don't get cut off or overlap the footer.
    if (y > 740) {
      doc.addPage()
      y = 56
    }
  })

  y += 20
  doc.setDrawColor(215, 229, 224)
  doc.line(margin, y, pageWidth - margin, y)
  y += 20

  doc.setFont('helvetica', 'italic')
  doc.setFontSize(8.5)
  doc.setTextColor(140, 150, 148)
  const disclaimer =
    'This report is generated by an automated image-colorimetry tool for point-of-care ' +
    'reference purposes only. It is not a certified diagnostic result and should not replace ' +
    'professional medical testing or advice.'
  // Wraps the disclaimer text to fit within the page margins rather than
  // running off the edge, since jsPDF does not wrap text automatically.
  const wrapped = doc.splitTextToSize(disclaimer, pageWidth - margin * 2)
  doc.text(wrapped, margin, y)

  // Strip the original file's extension (e.g. ".jpg") so the downloaded
  // report is named like "my-strip-report.pdf" instead of
  // "my-strip.jpg-report.pdf".
  const safeName = (filename || 'strip-result').replace(/\.[^/.]+$/, '')
  doc.save(`${safeName}-report.pdf`)
}
