import jsPDF from 'jspdf'

/**
 * Generates a clean, printable PDF report for a single strip analysis
 * and triggers a download.
 */
export function exportResultsToPDF({ filename, results, timestamp }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 48
  let y = 56

  // Header band
  doc.setFillColor(13, 124, 102) // teal
  doc.rect(0, 0, pageWidth, 8, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(16, 35, 31)
  doc.text('Urine Test Strip Analysis Report', margin, y)

  y += 22
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(90, 100, 98)
  const dateStr = timestamp ? new Date(timestamp).toLocaleString() : new Date().toLocaleString()
  doc.text(`Sample file: ${filename || 'uploaded image'}`, margin, y)
  y += 14
  doc.text(`Generated: ${dateStr}`, margin, y)
  y += 14
  doc.text('Method: Colorimetric image analysis (nearest-match against reference chart)', margin, y)

  y += 30
  doc.setDrawColor(215, 229, 224)
  doc.line(margin, y, pageWidth - margin, y)
  y += 28

  // Table header
  const col = {
    param: margin,
    swatch: margin + 140,
    rgb: margin + 200,
    result: margin + 340,
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(16, 35, 31)
  doc.text('Parameter', col.param, y)
  doc.text('Color', col.swatch, y)
  doc.text('Detected RGB', col.rgb, y)
  doc.text('Result', col.result, y)
  y += 10
  doc.setDrawColor(215, 229, 224)
  doc.line(margin, y, pageWidth - margin, y)
  y += 18

  doc.setFont('helvetica', 'normal')

  Object.entries(results || {}).forEach(([parameter, data]) => {
    const [r, g, b] = data.detected_rgb || [255, 255, 255]

    doc.setTextColor(16, 35, 31)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text(parameter, col.param, y + 4)

    doc.setFillColor(r, g, b)
    doc.setDrawColor(200, 200, 200)
    doc.circle(col.swatch + 8, y, 8, 'FD')

    doc.setFont('courier', 'normal')
    doc.setFontSize(9.5)
    doc.setTextColor(90, 100, 98)
    doc.text(`${r}, ${g}, ${b}`, col.rgb, y + 4)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10.5)
    doc.setTextColor(13, 87, 72)
    doc.text(String(data.result), col.result, y + 4)

    y += 30

    if (y > 740) {
      doc.addPage()
      y = 56
    }
  })

  y += 20
  doc.setDrawColor(215, 229, 224)
  doc.line(margin, y, pageWidth - margin, y)
  y += 20

  doc.setFont('helvetica', 'italic')
  doc.setFontSize(8.5)
  doc.setTextColor(140, 150, 148)
  const disclaimer =
    'This report is generated by an automated image-colorimetry tool for point-of-care ' +
    'reference purposes only. It is not a certified diagnostic result and should not replace ' +
    'professional medical testing or advice.'
  const wrapped = doc.splitTextToSize(disclaimer, pageWidth - margin * 2)
  doc.text(wrapped, margin, y)

  const safeName = (filename || 'strip-result').replace(/\.[^/.]+$/, '')
  doc.save(`${safeName}-report.pdf`)
}
